version: '3.3'
services:
  app:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - postgres
    networks:
      - projet
  postgres:
    container_name: postgres
    image: postgres:9
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - projet
networks:
    projet:
        driver: bridge